server:
  port: 8080

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://db:5432/store
    username: ${DATABASE_USERNAME:store}
    password: ${DATABASE_PASSWORD:devpass}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: orders

  flyway:
    enabled: true
    schemas: orders
    locations: classpath:db/migration